server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${peer}/eureka/
  instance:
    hostname: ${hostname}
spring:
  profiles: ${hostname}   