spring:
  application:
    name: spring-cloud-eureka-feign-client
server:
  port: 8080 
eureka:
  datacenter: cloud
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/